### ISSUE TITLE
[BUG] ImportError: cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by Amazon90** [Sanster/lama-cleaner#389]
```

(base) C:\Users\28622>conda activate lama

(lama) C:\Users\28622>lama-cleaner --model=lama --device=cuda --port=8080
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.11
- torch: 1.13.1+cu117
- torchvision: 0.14.1+cu117
- Pillow: 10.0.1
- diffusers: 0.16.1
- transformers: 4.27.4
- opencv-python: 4.8.1.78
- xformers: N/A
- accelerate: N/A
- lama-cleaner: 1.2.3
- rembg: N/A
- realesrgan: N/A
- gfpgan: N/A

Traceback (most recent call last):
  File "D:\miniconda3\envs\lama\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\envs\lama\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\miniconda3\envs\lama\Scripts\lama-cleaner.exe\__main__.py", line 7, in <module>
    sys.exit(entry_point())
  File "D:\miniconda3\envs\lama\lib\site-packages\lama_cleaner\__init__.py", line 16, in entry_point
    from lama_cleaner.server import main
  File "D:\miniconda3\envs\lama\lib\site-packages\lama_cleaner\server.py", line 44, in <module>
    from flask import (
  File "D:\miniconda3\envs\lama\lib\site-packages\flask\__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "D:\miniconda3\envs\lama\lib\site-packages\flask\app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (D:\miniconda3\envs\lama\lib\site-packages\werkzeug\urls.py)

(lama) C:\Users\28622>pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch==1.13.1+cu117 in d:\miniconda3\envs\lama\lib\site-packages (1.13.1+cu117)
Requirement already satisfied: torchvision==0.14.1+cu117 in d:\miniconda3\envs\lama\lib\site-packages (0.14.1+cu117)
Requirement already satisfied: torchaudio==0.13.1 in d:\miniconda3\envs\lama\lib\site-packages (0.13.1+cu117)
Requirement already satisfied: typing-extensions in d:\miniconda3\envs\lama\lib\site-packages (from torch==1.13.1+cu117) (4.8.0)
Requirement already satisfied: numpy in d:\miniconda3\envs\lama\lib\site-packages (from torchvision==0.14.1+cu117) (1.26.0)
Requirement already satisfied: requests in d:\miniconda3\envs\lama\lib\site-packages (from torchvision==0.14.1+cu117) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\miniconda3\envs\lama\lib\site-packages (from torchvision==0.14.1+cu117) (10.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\miniconda3\envs\lama\lib\site-packages (from requests->torchvision==0.14.1+cu117) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in d:\miniconda3\envs\lama\lib\site-packages (from requests->torchvision==0.14.1+cu117) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\miniconda3\envs\lama\lib\site-packages (from requests->torchvision==0.14.1+cu117) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in d:\miniconda3\envs\lama\lib\site-packages (from requests->torchvision==0.14.1+cu117) (2023.7.22)

(lama) C:\Users\28622>pip install lama-cleaner
Requirement already satisfied: lama-cleaner in d:\miniconda3\envs\lama\lib\site-packages (1.2.3)
Requirement already satisfied: torch>=1.9.0 in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (1.13.1+cu117)
Requirement already satisfied: opencv-python in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (4.8.1.78)
Requirement already satisfied: flask==2.2.3 in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (2.2.3)
Requirement already satisfied: flask-socketio in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (5.3.6)
Requirement already satisfied: simple-websocket in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (0.10.1)
Requirement already satisfied: flask-cors in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (4.0.0)
Requirement already satisfied: flaskwebgui==0.3.5 in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (0.3.5)
Requirement already satisfied: pydantic in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (2.4.2)
Requirement already satisfied: rich in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (13.6.0)
Requirement already satisfied: loguru in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (0.7.2)
Requirement already satisfied: yacs in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (0.1.8)
Requirement already satisfied: diffusers==0.16.1 in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (0.16.1)
Requirement already satisfied: transformers==4.27.4 in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (4.27.4)
Requirement already satisfied: gradio in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (3.46.0)
Requirement already satisfied: piexif==1.1.3 in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (1.1.3)
Requirement already satisfied: safetensors in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (0.3.3)
Requirement already satisfied: omegaconf in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (2.3.0)
Requirement already satisfied: controlnet-aux==0.0.3 in d:\miniconda3\envs\lama\lib\site-packages (from lama-cleaner) (0.0.3)
Requirement already satisfied: Pillow in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (10.0.1)
Requirement already satisfied: einops in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.7.0)
Requirement already satisfied: filelock in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (3.12.4)
Requirement already satisfied: huggingface-hub in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.17.3)
Requirement already satisfied: importlib-metadata in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (6.8.0)
Requirement already satisfied: numpy in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (1.26.0)
Requirement already satisfied: scikit-image in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.22.0)
Requirement already satisfied: scipy in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (1.11.3)
Requirement already satisfied: timm in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.9.7)
Requirement already satisfied: torchvision in d:\miniconda3\envs\lama\lib\site-packages (from controlnet-aux==0.0.3->lama-cleaner) (0.14.1+cu117)
Requirement already satisfied: regex!=2019.12.17 in d:\miniconda3\envs\lama\lib\site-packages (from diffusers==0.16.1->lama-cleaner) (2023.10.3)
Requirement already satisfied: requests in d:\miniconda3\envs\lama\lib\site-packages (from diffusers==0.16.1->lama-cleaner) (2.31.0)
Requirement already satisfied: Werkzeug>=2.2.2 in d:\miniconda3\envs\lama\lib\site-packages (from flask==2.2.3->lama-cleaner) (3.0.0)
Requirement already satisfied: Jinja2>=3.0 in d:\miniconda3\envs\lama\lib\site-packages (from flask==2.2.3->lama-cleaner) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in d:\miniconda3\envs\lama\lib\site-packages (from flask==2.2.3->lama-cleaner) (2.1.2)
Requirement already satisfied: click>=8.0 in d:\miniconda3\envs\lama\lib\site-packages (from flask==2.2.3->lama-cleaner) (8.1.7)
Requirement already satisfied: whichcraft in d:\miniconda3\envs\lama\lib\site-packages (from flaskwebgui==0.3.5->lama-cleaner) (0.6.1)
Requirement already satisfied: packaging>=20.0 in d:\miniconda3\envs\lama\lib\site-packages (from transformers==4.27.4->lama-cleaner) (23.2)
Requirement already satisfied: pyyaml>=5.1 in d:\miniconda3\envs\lama\lib\site-packages (from transformers==4.27.4->lama-cleaner) (6.0.1)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\miniconda3\envs\lama\lib\site-packages (from transformers==4.27.4->lama-cleaner) (0.13.3)
Requirement already satisfied: tqdm>=4.27 in d:\miniconda3\envs\lama\lib\site-packages (from transformers==4.27.4->lama-cleaner) (4.66.1)
Requirement already satisfied: typing-extensions in d:\miniconda3\envs\lama\lib\site-packages (from torch>=1.9.0->lama-cleaner) (4.8.0)
Requirement already satisfied: python-socketio>=5.0.2 in d:\miniconda3\envs\lama\lib\site-packages (from flask-socketio->lama-cleaner) (5.9.0)
Requirement already satisfied: aiofiles<24.0,>=22.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (5.1.2)
Requirement already satisfied: fastapi in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (0.103.2)
Requirement already satisfied: ffmpy in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (0.3.1)
Requirement already satisfied: gradio-client==0.5.3 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (0.5.3)
Requirement already satisfied: httpx in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (0.25.0)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (6.1.0)
Requirement already satisfied: markupsafe~=2.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (2.1.3)
Requirement already satisfied: matplotlib~=3.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (3.8.0)
Requirement already satisfied: orjson~=3.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (3.9.7)
Requirement already satisfied: pandas<3.0,>=1.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (2.1.1)
Requirement already satisfied: pydub in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (0.25.1)
Requirement already satisfied: python-multipart in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (0.0.6)
Requirement already satisfied: semantic-version~=2.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (2.10.0)
Requirement already satisfied: uvicorn>=0.14.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (0.23.2)
Requirement already satisfied: websockets<12.0,>=10.0 in d:\miniconda3\envs\lama\lib\site-packages (from gradio->lama-cleaner) (11.0.3)
Requirement already satisfied: fsspec in d:\miniconda3\envs\lama\lib\site-packages (from gradio-client==0.5.3->gradio->lama-cleaner) (2023.9.2)
Requirement already satisfied: annotated-types>=0.4.0 in d:\miniconda3\envs\lama\lib\site-packages (from pydantic->lama-cleaner) (0.5.0)
Requirement already satisfied: pydantic-core==2.10.1 in d:\miniconda3\envs\lama\lib\site-packages (from pydantic->lama-cleaner) (2.10.1)
Requirement already satisfied: colorama>=0.3.4 in d:\miniconda3\envs\lama\lib\site-packages (from loguru->lama-cleaner) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in d:\miniconda3\envs\lama\lib\site-packages (from loguru->lama-cleaner) (1.1.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in d:\miniconda3\envs\lama\lib\site-packages (from omegaconf->lama-cleaner) (4.9.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\miniconda3\envs\lama\lib\site-packages (from rich->lama-cleaner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\miniconda3\envs\lama\lib\site-packages (from rich->lama-cleaner) (2.16.1)
Requirement already satisfied: wsproto in d:\miniconda3\envs\lama\lib\site-packages (from simple-websocket->lama-cleaner) (1.2.0)
Requirement already satisfied: jsonschema>=3.0 in d:\miniconda3\envs\lama\lib\site-packages (from altair<6.0,>=4.2.0->gradio->lama-cleaner) (4.19.1)
Requirement already satisfied: toolz in d:\miniconda3\envs\lama\lib\site-packages (from altair<6.0,>=4.2.0->gradio->lama-cleaner) (0.12.0)
Requirement already satisfied: mdurl~=0.1 in d:\miniconda3\envs\lama\lib\site-packages (from markdown-it-py>=2.2.0->rich->lama-cleaner) (0.1.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\miniconda3\envs\lama\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (1.1.1)
Requirement already satisfied: cycler>=0.10 in d:\miniconda3\envs\lama\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (0.12.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\miniconda3\envs\lama\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (4.43.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\miniconda3\envs\lama\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (1.4.5)
Requirement already satisfied: pyparsing>=2.3.1 in d:\miniconda3\envs\lama\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in d:\miniconda3\envs\lama\lib\site-packages (from matplotlib~=3.0->gradio->lama-cleaner) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in d:\miniconda3\envs\lama\lib\site-packages (from pandas<3.0,>=1.0->gradio->lama-cleaner) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in d:\miniconda3\envs\lama\lib\site-packages (from pandas<3.0,>=1.0->gradio->lama-cleaner) (2023.3)
Requirement already satisfied: bidict>=0.21.0 in d:\miniconda3\envs\lama\lib\site-packages (from python-socketio>=5.0.2->flask-socketio->lama-cleaner) (0.22.1)
Requirement already satisfied: python-engineio>=4.7.0 in d:\miniconda3\envs\lama\lib\site-packages (from python-socketio>=5.0.2->flask-socketio->lama-cleaner) (4.7.1)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\miniconda3\envs\lama\lib\site-packages (from requests->diffusers==0.16.1->lama-cleaner) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in d:\miniconda3\envs\lama\lib\site-packages (from requests->diffusers==0.16.1->lama-cleaner) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\miniconda3\envs\lama\lib\site-packages (from requests->diffusers==0.16.1->lama-cleaner) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in d:\miniconda3\envs\lama\lib\site-packages (from requests->diffusers==0.16.1->lama-cleaner) (2023.7.22)
Requirement already satisfied: h11>=0.8 in d:\miniconda3\envs\lama\lib\site-packages (from uvicorn>=0.14.0->gradio->lama-cleaner) (0.14.0)
Requirement already satisfied: anyio<4.0.0,>=3.7.1 in d:\miniconda3\envs\lama\lib\site-packages (from fastapi->gradio->lama-cleaner) (3.7.1)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in d:\miniconda3\envs\lama\lib\site-packages (from fastapi->gradio->lama-cleaner) (0.27.0)
Requirement already satisfied: httpcore<0.19.0,>=0.18.0 in d:\miniconda3\envs\lama\lib\site-packages (from httpx->gradio->lama-cleaner) (0.18.0)
Requirement already satisfied: sniffio in d:\miniconda3\envs\lama\lib\site-packages (from httpx->gradio->lama-cleaner) (1.3.0)
Requirement already satisfied: zipp>=0.5 in d:\miniconda3\envs\lama\lib\site-packages (from importlib-metadata->controlnet-aux==0.0.3->lama-cleaner) (3.17.0)
Requirement already satisfied: networkx>=2.8 in d:\miniconda3\envs\lama\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (3.1)
Requirement already satisfied: imageio>=2.27 in d:\miniconda3\envs\lama\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (2.31.5)
Requirement already satisfied: tifffile>=2022.8.12 in d:\miniconda3\envs\lama\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (2023.9.26)
Requirement already satisfied: lazy_loader>=0.3 in d:\miniconda3\envs\lama\lib\site-packages (from scikit-image->controlnet-aux==0.0.3->lama-cleaner) (0.3)
Requirement already satisfied: exceptiongroup in d:\miniconda3\envs\lama\lib\site-packages (from anyio<4.0.0,>=3.7.1->fastapi->gradio->lama-cleaner) (1.1.3)
Requirement already satisfied: attrs>=22.2.0 in d:\miniconda3\envs\lama\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->lama-cleaner) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\miniconda3\envs\lama\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->lama-cleaner) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in d:\miniconda3\envs\lama\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->lama-cleaner) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in d:\miniconda3\envs\lama\lib\site-packages (from jsonschema>=3.0->altair<6.0,>=4.2.0->gradio->lama-cleaner) (0.10.3)
Requirement already satisfied: six>=1.5 in d:\miniconda3\envs\lama\lib\site-packages (from python-dateutil>=2.7->matplotlib~=3.0->gradio->lama-cleaner) (1.16.0)

(lama) C:\Users\28622>lama-cleaner --model=lama --device=cuda --port=8080
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.11
- torch: 1.13.1+cu117
- torchvision: 0.14.1+cu117
- Pillow: 10.0.1
- diffusers: 0.16.1
- transformers: 4.27.4
- opencv-python: 4.8.1.78
- xformers: N/A
- accelerate: N/A
- lama-cleaner: 1.2.3
- rembg: N/A
- realesrgan: N/A
- gfpgan: N/A

Traceback (most recent call last):
  File "D:\miniconda3\envs\lama\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\miniconda3\envs\lama\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\miniconda3\envs\lama\Scripts\lama-cleaner.exe\__main__.py", line 7, in <module>
    sys.exit(entry_point())
  File "D:\miniconda3\envs\lama\lib\site-packages\lama_cleaner\__init__.py", line 16, in entry_point
    from lama_cleaner.server import main
  File "D:\miniconda3\envs\lama\lib\site-packages\lama_cleaner\server.py", line 44, in <module>
    from flask import (
  File "D:\miniconda3\envs\lama\lib\site-packages\flask\__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "D:\miniconda3\envs\lama\lib\site-packages\flask\app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (D:\miniconda3\envs\lama\lib\site-packages\werkzeug\urls.py)

(lama) C:\Users\28622>
```

**Comment by Kiminjo** [comment]
I also have same problem

**Comment by Kiminjo** [comment]
I don't know how to solve the problem that happened later. However, I found out how to solve the first problem you wrote.

This problem arises when a library called werkzeug with dependencies was recently updated to 3.0.0. Therefore, clone the repository and add `werkzeug==2.2.2` to `requirements.txt`. And try running `pip install -r requirements.txt`.

And running `python main.py` will solve the problem.

**Comment by Sanster** [comment]
@Kiminjo Thank you very much, I have fixed this issue in version 1.2.4.

**Comment by Din-Avrunin** [comment]
how do you fix this problem for azure? even if i change the requirements file it still fails on azure (it works on local computer though)

**Comment by Amazon90** [comment]
> how do you fix this problem for azure? even if i change the requirements file it still fails on azure (it works on local computer though)

Sorry, I haven't deployed it on the azure server, so I can't answer your question.

**Comment by juangonzalezAuctus** [comment]
> how do you fix this problem for azure? even if i change the requirements file it still fails on azure (it works on local computer though)

Same problem, if you ever resolved it, please let me know

**Comment by JackYouk** [comment]
Was having the same issue on my azure VM trying to run mitmproxy. This fixed it: ```pip uninstall -y Werkzeug && pip install Werkzeug==2.3.6```
